# Set the version of docker compose to use
version: '3.9'

# The containers that compose the project
services:
   db:
      image: postgres
      restart: always
      container_name: dwallet-integration-tests
      ports:
         - '5433:5432'
      environment:
         POSTGRES_USER: postgres
         POSTGRES_PASSWORD: dwallettests
         POSTGRES_DB: dwallet-tests
